# Docs for the Azure Web Apps Deploy action:
# https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure:
# https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - student-management-prem

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore StudentManagement/StudentManagement.csproj

      - name: Build API
        run: dotnet build StudentManagement/StudentManagement.csproj --configuration Release --no-restore

      - name: Publish API
        run: dotnet publish StudentManagement/StudentManagement.csproj --configuration Release --output "${{ env.DOTNET_ROOT }}/myapp" --no-build

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ${{ env.DOTNET_ROOT }}/myapp

  deploy:
    runs-on: windows-latest

    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_59379C428567418E8365029D777D542E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9FC2699C3D63460A806CB99A3E1F323E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BC9446F001144B12931C13BDD40B74BB }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'student-management-prem'
          slot-name: 'Production'
          package: .
